### ISSUE TITLE
Add README.md file

### ISSUE THREAD

**Issue by LudiscapeXApi** [Andy77550/curriculum_vitae_base#2]
Add README.md file who explain plugin functions

**Comment by Andy77550** [comment]
Bonjour,

Les documents ont été ajouté,

Je les mettraient à jour quand il y aura des modifications à apporter

Cordialement,

Andy Vespuce.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le mar. 17 nov. 2020 à 10:34, DamienLyon <notifications@github.com> a
écrit :
